version: '3'
services:
  apm-agent:
    image: docker.elastic.co/apm/apm-server:7.6.1
    depends_on:
      - elasticsearch
      - kibana
    cap_add: [ "CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID" ]
    cap_drop: [ "ALL" ]
    restart: on-failure
    networks:
       net:
    ports:
      - "8200:8200"
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    depends_on:
    - elasticsearch
    restart: on-failure
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - net
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  elasticsearch:
    image: elasticsearch:7.6.1
    networks:
      net:
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - network.host=0.0.0.0
      - http.host=0.0.0.0
  crypto-search-service:
    ports:
      - "8000:8000"
    build:
      context: crypto-search-service
      dockerfile: Dockerfile
    healthcheck:
      test: curl --fail http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    restart: always
    networks:
      net:
    environment:
      - "INDEX_NAME=cryptos"
      - "ELASTIC_URL=http://elasticsearch:9200"
      - "PORT=8000"
  crypto-indexer:
    build:
      context: crypto-indexer
      dockerfile: Dockerfile
    healthcheck:
      test: curl --fail http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    restart: on-failure
    networks:
      net:
    environment:
      - "FINN_HUB_API_KEY=$FINN_HUB_API_KEY"
      - "FINN_HUB_PROTOCOL=https"
      - "FINN_HUB_HOST_PORT=finnhub.io"
      - "INDEX_NAME=cryptos"
      - "ELASTIC_URL=http://elasticsearch:9200"
networks:
  net: